"""initial schema

Revision ID: 19a5fe877349
Revises: 
Create Date: 2026-07-12 22:12:23.144597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19a5fe877349'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_locks',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('integer_value', sa.Integer(), nullable=False),
    sa.Column('token', sa.LargeBinary(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('login_throttles',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_table('scheduler_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('last_user_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('service_health',
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('service')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('username_normalized', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'DELETING', name='userstate'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_bootstrap', sa.Boolean(), nullable=False),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_normalized')
    )
    op.create_table('workflow_diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('basename', sa.String(length=255), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_version', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_diagnostics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_diagnostics_basename'), ['basename'], unique=False)

    op.create_table('workflow_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_key', sa.String(length=500), nullable=False),
    sa.Column('basename', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('workflow_version', sa.String(length=64), nullable=False),
    sa.Column('contract_schema_version', sa.String(length=64), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('ui_graph_sha256', sa.String(length=64), nullable=False),
    sa.Column('api_graph_sha256', sa.String(length=64), nullable=False),
    sa.Column('contract_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_ui_json', sa.JSON(), nullable=False),
    sa.Column('source_api_json', sa.JSON(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('resolved_contract_json', sa.JSON(), nullable=False),
    sa.Column('runtime_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('VALID', 'INVALID', 'STALE', name='workflowstate'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key', name='uq_workflow_identity')
    )
    with op.batch_alter_table('workflow_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_profiles_basename'), ['basename'], unique=False)
        batch_op.create_index('ix_workflow_profiles_current', ['is_current', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_profiles_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)

    op.create_table('generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'DISPATCHING', 'RUNNING', 'CANCEL_REQUESTED', 'SUCCEEDED', 'CANCELLED_WITH_ARTIFACTS', 'CANCELLED_WITHOUT_ARTIFACTS', 'FAILED_WITH_ARTIFACTS', 'FAILED_WITHOUT_ARTIFACTS', 'INTERRUPTED', name='generationstatus'), nullable=False),
    sa.Column('queue_seq', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('comfyui_client_id', sa.String(length=64), nullable=False),
    sa.Column('comfyui_prompt_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_profile_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_display_name', sa.String(length=255), nullable=False),
    sa.Column('workflow_version', sa.String(length=64), nullable=False),
    sa.Column('contract_schema_version', sa.String(length=64), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('ui_graph_sha256', sa.String(length=64), nullable=False),
    sa.Column('api_graph_sha256', sa.String(length=64), nullable=False),
    sa.Column('contract_sha256', sa.String(length=64), nullable=False),
    sa.Column('resolved_contract_json', sa.JSON(), nullable=False),
    sa.Column('requested_controls_json', sa.JSON(), nullable=False),
    sa.Column('effective_controls_json', sa.JSON(), nullable=False),
    sa.Column('resolved_seeds_json', sa.JSON(), nullable=False),
    sa.Column('selected_preset', sa.String(length=100), nullable=True),
    sa.Column('requested_outputs_json', sa.JSON(), nullable=False),
    sa.Column('final_prompt', sa.Text(), nullable=False),
    sa.Column('compiled_graph_json', sa.JSON(), nullable=False),
    sa.Column('compiled_graph_sha256', sa.String(length=64), nullable=False),
    sa.Column('submitted_graph_json', sa.JSON(), nullable=True),
    sa.Column('submitted_graph_sha256', sa.String(length=64), nullable=True),
    sa.Column('current_stage_id', sa.String(length=100), nullable=True),
    sa.Column('current_stage_label', sa.String(length=255), nullable=True),
    sa.Column('current_stage_sequence', sa.Integer(), nullable=True),
    sa.Column('best_available_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_count', sa.Integer(), nullable=False),
    sa.Column('final_artifact_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_diagnostics_json', sa.JSON(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_delete', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_profile_id'], ['workflow_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index('ix_generations_owner_created', ['owner_id', 'accepted_at', 'id'], unique=False)
        batch_op.create_index('ix_generations_prompt_id', ['comfyui_prompt_id'], unique=False)
        batch_op.create_index('ix_generations_queue', ['status', 'queue_seq'], unique=False)

    op.create_table('sessions',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'MASK', name='uploadkind'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index('ix_upload_owner_created', ['owner_id', 'created_at'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gallery_scale', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('output_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('state', sa.Enum('PROVISIONAL', 'SUPERSEDED', 'BEST_AVAILABLE', 'FINAL', 'PARTIAL', name='artifactstate'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('batch_index', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_node_id', sa.String(length=100), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('source_subfolder', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('usable_on_cancel', sa.Boolean(), nullable=False),
    sa.Column('usable_on_failure', sa.Boolean(), nullable=False),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.Column('best_available', sa.Boolean(), nullable=False),
    sa.Column('emitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id', 'output_id', 'sequence', 'batch_index', 'sha256', name='uq_artifact_generation_output_hash'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('thumbnail_path')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_generation_sequence', ['generation_id', 'sequence', 'batch_index'], unique=False)
        batch_op.create_index('ix_artifact_owner', ['owner_id', 'id'], unique=False)

    op.create_table('generation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_events', schema=None) as batch_op:
        batch_op.create_index('ix_generation_events_generation_id', ['generation_id', 'id'], unique=False)
        batch_op.create_index('ix_generation_events_owner_id', ['owner_id', 'id'], unique=False)

    op.create_table('generation_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id', 'control_id', name='uq_generation_upload')
    )
    with op.batch_alter_table('generation_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_uploads_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_uploads_upload_id'), ['upload_id'], unique=False)

    op.create_table('prompt_assistant_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('prompt_before', sa.Text(), nullable=False),
    sa.Column('creative_direction', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('template_version', sa.String(length=64), nullable=False),
    sa.Column('ollama_output', sa.Text(), nullable=True),
    sa.Column('raw_response_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_assistant_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_assistant_runs_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index('ix_prompt_run_owner_created', ['owner_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_assistant_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_run_owner_created')
        batch_op.drop_index(batch_op.f('ix_prompt_assistant_runs_generation_id'))

    op.drop_table('prompt_assistant_runs')
    with op.batch_alter_table('generation_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_uploads_upload_id'))
        batch_op.drop_index(batch_op.f('ix_generation_uploads_generation_id'))

    op.drop_table('generation_uploads')
    with op.batch_alter_table('generation_events', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_events_owner_id')
        batch_op.drop_index('ix_generation_events_generation_id')

    op.drop_table('generation_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_owner')
        batch_op.drop_index('ix_artifact_generation_sequence')

    op.drop_table('artifacts')
    op.drop_table('user_preferences')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index('ix_upload_owner_created')

    op.drop_table('uploads')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index('ix_generations_queue')
        batch_op.drop_index('ix_generations_prompt_id')
        batch_op.drop_index('ix_generations_owner_created')

    op.drop_table('generations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('workflow_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_profiles_workflow_id'))
        batch_op.drop_index('ix_workflow_profiles_current')
        batch_op.drop_index(batch_op.f('ix_workflow_profiles_basename'))

    op.drop_table('workflow_profiles')
    with op.batch_alter_table('workflow_diagnostics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_diagnostics_basename'))

    op.drop_table('workflow_diagnostics')
    op.drop_table('users')
    op.drop_table('service_health')
    op.drop_table('scheduler_state')
    op.drop_table('login_throttles')
    op.drop_table('app_locks')
    # ### end Alembic commands ###
